easy_admin:
    entities:
        # List the entity class name you want to manage
        ChampsClinique:
            class: App\Entity\ChampsClinique
        Categorie:
            class: App\Entity\Categorie
        SousCategorie:
            class: App\Entity\SousCategorie
        Question:
            class: App\Entity\Question
        Reponse:
            class: App\Entity\Reponse
        Role:
            class: App\Entity\Role
        Score:
            class: App\Entity\Score
        User:
            class: App\Entity\User
        Upload:
            class: App\Entity\Upload
        CasClinique:
            class: App\Entity\CasClinique
        TestVideo:
            class: App\Entity\TestVideo
            form:
                fields:
                    - { property: 'videoFile', type: 'file', label: 'Uploader une vidéo' }
                    - { property: 'name',  label: 'Nom du test'}
                    - {property: 'idSousCategorie', label: 'Sous-catégorie'}
            #form: {field : "videos", type : "upload"}

    design:
        menu:
            - { entity: 'ChampsClinique', rel: 'champs-clinique'}
            - { entity: 'Categorie', rel: 'categorie'}
            - { entity: 'SousCategorie', rel: 'sous-categorie'}
            - { entity: 'Question', rel: 'questions'}
            - { entity: 'Reponse', rel: 'reponses'}
            - { entity: 'Role', rel: 'roles'}
            - { entity: 'Score', rel: 'score'}
            - { entity: 'TestVideo', rel: 'test-video'}
            - { entity: 'User', rel: 'user'}
            - { label: 'Ajouter des utilisateurs', url: '%router.request_context.base_url%/ERCPhysio/public/upload' }
