easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\ChampsClinique
        - App\Entity\Categorie
        - App\Entity\SousCategorie
        - App\Entity\Question
        - App\Entity\Reponse
        - App\Entity\Role
        - App\Entity\Score
        - App\Entity\TestVideo
        - App\Entity\User
        - App\Entity\Upload
        - App\Entity\CasClinique
            #form: {field : "videos", type : "upload"}

    design:
        menu:
            - { entity: 'ChampsClinique', rel: 'champs-clinique'}
            - { entity: 'Categorie', rel: 'categorie'}
            - { entity: 'SousCategorie', rel: 'sous-categorie'}
            - { entity: 'Question', rel: 'questions'}
            - { entity: 'Reponse', rel: 'reponses'}
            - { entity: 'Role', rel: 'roles'}
            - { entity: 'Score', rel: 'score'}
            - { entity: 'TestVideo', rel: 'test-video'}
            - { entity: 'User', rel: 'user'}
            - { label: 'Ajouter des utilisateurs', url: '%router.request_context.base_url%/ERCPhysio/public/upload' }
