parameters:
    app.path.videos: /uploads/videos

vich_uploader:
    db_driver: orm
    mappings:
        videos:
            uri_prefix:         '%app.path.videos%'
            upload_destination: '%kernel.root_dir%/../public/uploads/videos'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
